// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using clickmedic.Models;

namespace clickmedic.Migrations
{
    [DbContext(typeof(MedicclickDBContext))]
    [Migration("20210311193706_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("clickmedic.Models.Alergia", b =>
                {
                    b.Property<int>("AlergiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Medicamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlergiaId");

                    b.ToTable("Alergias");
                });

            modelBuilder.Entity("clickmedic.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("FechaUltimaConsulta")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroExpediente")
                        .HasColumnType("int");

                    b.Property<string>("TipoSangre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("alergiasAlergiaId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.HasIndex("alergiasAlergiaId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("clickmedic.Models.Usuario", b =>
                {
                    b.HasOne("clickmedic.Models.Alergia", "alergias")
                        .WithMany()
                        .HasForeignKey("alergiasAlergiaId");

                    b.Navigation("alergias");
                });
#pragma warning restore 612, 618
        }
    }
}
